### ISSUE TITLE
[Bug]: CLI does not work for users using SSH with passphrase

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#231] opened 2022-06-21 14:28 UTC
### What kit and version are you using?

CLI

### What browser are you using?

n/a

### What operating system are you using?

Windows

### Actual Behavior

![image](https://user-images.githubusercontent.com/1815379/174824209-1a8f7994-4191-4130-be8a-6e0fc47ea3d6.png)

### Expected Behavior

I should be prompted for my passphrase.

### Reproduction

1. Setup your local ssh to use passphrases
2. Run `npx @this-dot/create-starter`
3. Get error

**Comment by danecando** [comment] 2022-08-30 14:05
Unable to reproduce. Closing this for now..

**Closed by danecando** 2022-08-30 14:05 UTC
Labels: bug
